---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 1.9.3
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.7.1"
  - PUPPET_VERSION="~> 3.7.2"
  - PUPPET_VERSION="~> 3.7.3"
  - PUPPET_VERSION="~> 3.7.4"
  - PUPPET_VERSION="~> 3.7.5"
